.node:
  image: node:10
  before_script:
    - npm install
  tags:
    - docker

cache:
  key: untracked
  paths:
  - node_modules/

stages:
  - lint
  - test
  - coverage


lint:
  extends: .node
  stage: lint
  script:
    - npm run lint

test:
  extends: .node
  stage: test
  script:
    - npm t

coverage:
  extends: .node
  stage: coverage
  script:
    - npm run coverage
